name: portfolio
description: "Portfolio developed in Flutter"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # UI packages
  google_fonts: ^6.1.0
  flex_color_scheme: ^7.3.1
  flutter_svg: ^2.0.9
  animated_toggle_switch: ^0.8.0
  
  # State management
  hooks_riverpod: ^2.4.9
  flutter_hooks: ^0.20.3
  riverpod_annotation: ^2.3.3
  
  # Localization
  easy_localization: ^3.0.3
  easy_logger: ^0.0.2
  
  # Navigation & URLs
  url_launcher: ^6.2.2
  url_strategy: ^0.2.0
  
  # Storage
  shared_preferences: ^2.2.2
  
  # Utils
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  intl: ^0.18.1
  collection: ^1.18.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  
  # Code generation
  build_runner: ^2.4.7
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.7
  
  # App icons & splash
  flutter_native_splash: ^2.3.8
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/icons/flags/
    - assets/icons/other/
    - assets/icons/software-development/
    - assets/images/
    - assets/translations/

  fonts:
    - family: BoxIcons
      fonts:
        - asset: assets/fonts/BoxIcons.ttf
    - family: FontAwesome
      fonts:
        - asset: assets/fonts/FontAwesome.ttf
    - family: OctIcons
      fonts:
        - asset: assets/fonts/OctIcons.ttf

flutter_native_splash:
  color: "#60a3d9"
  image: "assets/images/spinner-light.apng"
  color_dark: "#122035"
  image_dark: "assets/images/spinner-dark.apng"